version: '3'

services:
  reviews:
    image: adriennelim/ghrsea_express_module:reviews
    depends_on:
      - 'database'
    ports: 
      - '3001:3001'

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: testpw
    command: --default-authentication-plugin=mysql_native_password
    
